language: php
php:
  - 8.2
dist: focal
sudo: true
cache:
  directories:
    - $HOME/.composer/cache
services:
  - postgresql
addons:
  postgresql: '12'
  apt:
    packages:
      - libonig5
      - postgresql-12
      - postgresql-client-12
      - postgresql-12-postgis-3
env:
  global:
    - PGPORT=5433
    - PGUSER=travis
before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart
  - sleep 1
  - sudo mount -o remount,size=50% /var/ramfs
  - phpenv config-rm xdebug.ini
install:
  - composer self-update
  - composer install --prefer-dist --no-interaction
before_script:
  - psql -U travis -c 'create database travis_ci_test'
  - psql -U travis -c 'create extension postgis'
  - php init_db.php
script:
  - vendor/phpunit/phpunit/phpunit --stop-on-error --stop-on-failure
