language: php
php:
  - "8.3"
dist: focal
sudo: true
cache:
  directories:
    - $HOME/.composer/cache
services:
  - postgresql
addons:
  postgresql: "15"
  apt:
    packages:
      - libonig5
      - postgresql-15
      - postgresql-client-15
      - postgresql-15-postgis-3
env:
  global:
    - PGPORT=5433
    - PGUSER=travis
    - DB_PORT=5433
    - DB_DATABASE=travis_ci_test
    - DB_USERNAME=travis
    - DB_PASSWORD=travis
before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo systemctl stop postgresql@15-main
  - sudo systemctl start postgresql@15-main
  - sleep 1
  - sudo mount -o remount,size=50% /var/ramfs
  - phpenv config-rm xdebug.ini
install:
  - composer self-update
  - composer install --prefer-dist --no-interaction
before_script:
  - psql -U travis -c 'create database travis_ci_test'
  - psql -U travis -c 'create extension postgis'
  - psql -U travis -c "ALTER USER travis WITH PASSWORD 'travis';"
  - php init_db.php
script:
  - vendor/phpunit/phpunit/phpunit --stop-on-error --stop-on-failure
